codeline:
  client:
    address:
      url: https://codeline.free.beeceptor.com/address
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-databse: admin
      username: root
      password: example
      database: hexagonal