server:
  port: 8081

codeline:
  client:
    address:
      url: https://codeline.free.beeceptor.com/address

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: codeline